# Generated by Django 3.2.9 on 2021-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifs',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gifs',
            name='uploader_name',
            field=models.CharField(max_length=50),
        ),
    ]
